Candidat/Candidat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('login.urls'))),
    path('a/',include(('app.urls'))),
]

Candidat/app/urls.py
from django.contrib import admin
from django.urls import path
from .views import api, UserUpdateView,stat,filter

app_name = "app"
urlpatterns = [
    path('update/<int:pk>/',UserUpdateView.as_view(),name='update'),
    path('api/<int:pk>',api,name="api"),
    path('stat/<int:pk>',stat,name='stat'),
    path('filter/<str:url>',filter),
]

Candidat/login/urls.py
from django.contrib import admin
from django.urls import path
from .views import signin,signup, home, verify,logout,UserUpdateView

app_name = "login"
urlpatterns = [
    path('',home, name="home"),
    path('signin/<int:msg>',signin, name="sign"),
    path('signup/',signup, name="sigp"),
    path('verify/<int:msg>',verify, name="verify"),
    path('logout/',logout,name="logout"),
]

Candidat/app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Taburl(models.Model):
    basic = models.CharField(max_length=250)
    miniurl = models.CharField(max_length=9)
    user = models.ForeignKey(to=User,on_delete=models.CASCADE)
    nb = models.IntegerField(default=0)

Candidat/login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    code = models.CharField(max_length=25)
    user = models.OneToOneField(User,on_delete=models.CASCADE)

Candidat/app/views.py
from django.shortcuts import render
from django.views.generic.edit import UpdateView
from django.contrib.auth.models import  User
from .models import  Taburl

# Create your views here.
class UserUpdateView(UpdateView):
    model = User
    fields = ['username','first_name','last_name','email','password']
    template_name = 'user_update_form.html'
    success_url = "/"


def api(request,pk):
    import string
    import random
    if(request.method == "POST"):
        d = 1

        try:
            base = Taburl.objects.get(basic=request.POST['url'])
            #base.nb = base.nb + 1
            url = base.miniurl
        except Exception as x:
            while(d):
                url = [random.choice(string.ascii_letters + string.digits + '?!*-.,=@') for k in range(9)]
                url = "".join(url)
                try:
                    u = Taburl.objects.get(basic=url)
                except:
                    d = 0

            user = User.objects.get(id=pk)
            tab = Taburl()
            tab.user = user
            tab.basic = request.POST['url']
            tab.miniurl = url
            tab.nb = 0
            tab.save()

        return render(request, 'raccorcisor.html', {'ok': 1, 'msg': "127.0.0.1:8000/a/filter/" + url})
    else:
        return render(request,'raccorcisor.html',{'ok':0, 'msg': ""})

def stat(request, pk):
    user = User.objects.get(id=pk)
    try:
        hist = Taburl.objects.filter(user=user)
    except Exception as x:
        hist = []
    return render(request, 'stat.html',{"users":hist, "ok":1})

def filter(request,url):
    basic = Taburl.objects.get(miniurl=url)
    basic.nb = basic.nb + 1
    basic.save()
    return render(request,'filter.html',{"basic":basic.basic})

Candidat/login/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import  User
from django.contrib.auth import authenticate,login,logout as dj_logout
from .models import Profile
from django.contrib.auth.decorators import login_required
import smtplib
import ssl
from email import encoders
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from django.views.generic.edit import UpdateView


# Create your views here.
def signin(request,msg):
    print(msg)
    if(request.method == 'POST'):
        user = request.POST['login']
        pwd = request.POST['pwd']
        try:
            u = User.objects.get(username=user,password=pwd)
            login(request,u)
            return redirect('login:home')
        except Exception as x:
            return render(request, 'signin.html', {"msg": 1})
    else:
        return render(request, 'signin.html', {"msg": 0})

def signup(request):
    import string
    import random
    if(request.method == 'POST'):
        request.session['fname'] = request.POST['fname']
        request.session['lname'] = request.POST['lname']
        request.session['mail'] = request.POST['mail']
        request.session['user'] = request.POST['username']
        request.session['pwd'] = request.POST['pwd']

        code = [random.choice(string.ascii_letters) for i in range(50)]
        code = "".join(code)
        request.session['code'] = code

        sendmail(request.session['mail'],request.session['user'],code)
        return redirect('login:verify',0)
    else:
        return render(request,'signup.html')

def home(request):
    return render(request,'blank.html')

def verify(request,msg):
    if(request.method == "POST"):
        code = request.POST['code']
        if (code == request.session['code']):
            u = User()
            u.username = request.session['user']
            u.email = request.session['mail']
            u.first_name = request.session['fname']
            u.last_name = request.session['lname']
            u.password = request.session['pwd']
            u.save()
            p = Profile(code=code, user=u)
            p.save()
            request.session.clear()
            return redirect('login:sign',0)
        else:
            return render(request, 'verify.html',{"msg":1})
    else:
        return render(request,'verify.html', {"msg":0})


def sendmail(mail,user,code):
    port = 465  # For SSL
    # Create a secure SSL context
    context = ssl.create_default_context()
    with smtplib.SMTP_SSL("smtp.gmail.com", port, context=context) as server:
        server.login("azerch.1996@gmail.com", '01246790aA')

        msg = MIMEMultipart()
        msg['from'] = 'Django Candidat'
        msg['to'] = mail
        msg['Subject'] = "Last step to register"
        message = '<h1> Welcome {} </h1> <br> <br> <img src="https://www.lhotellerie-restauration.fr/journal/equipement-materiel/2018-06/img/tablhotel.jpg" alt="check connection" <br><br><br><br><br><br> Your verifying code is: <underline> {} </underline>'.format(user,code)
        msg.attach(MIMEText(message, 'html'))
        server.sendmail('azerch.1996@gmail.com"', mail, msg.as_string())

@login_required
def logout(request):
    dj_logout(request)
    return render(request,'blank.html')

class UserUpdateView(UpdateView):
    model = User
    fields = ['username','first_name','last_name','email','password']
    template_name = 'user_update_form.html'
    success_url = "/"

Candidat/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    {% block title %}
    <title >Home</title>
    {% endblock %}
     <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
</head>
<body>
{% block principale %}


{% endblock %}
</body>
</html>

Candidat/templates/blank.html
<!DOCTYPE html>
<html dir="ltr" lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon.png' %}">
   <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    {% block title %}
    {% endblock %}
</head>

<body>

    <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full"
        data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

        <header class="topbar" data-navbarbg="skin5">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header" data-logobg="skin6">

                    <a class="navbar-brand" href="{% url 'login:home' %}">
                        <span class="logo-text">
                            <!-- dark Logo text -->
                            <img src="{% static 'logo-text.jpg' %}" alt="homepage" />
                        </span>
                    </a>
                    <a class="nav-toggler waves-effect waves-light text-dark d-block d-md-none"
                        href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                </div>

                <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
                    <ul class="navbar-nav d-none d-md-block d-lg-none">
                        <li class="nav-item">
                            <a class="nav-toggler nav-link waves-effect waves-light text-white"
                                href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                        </li>
                    </ul>
                </div>

            </nav>
        </header>

        <aside class="left-sidebar" data-sidebarbg="skin6">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <!-- User Profile-->
                        {% if request.user.is_authenticated %}
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'app:update' request.user.id %}"
                                aria-expanded="false">
                                <i class="fa fa-user" aria-hidden="true"></i>
                                <span class="hide-menu">My profile</span>
                            </a>
                        </li>
                        <li class="sidebar-item pt-2">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'app:api' request.user.id %}"
                                aria-expanded="false">
                                <i class="far fa-clock" aria-hidden="true"></i>
                                <span class="hide-menu">Raccorcisor</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{% url 'app:stat' request.user.id %}"
                                aria-expanded="false">
                                <i class="fa fa-table" aria-hidden="true"></i>
                                <span class="hide-menu">My statistics</span>
                            </a>
                        </li>
                        {% endif %}

                        {% if request.user.is_authenticated %}
                            <li class="text-center p-20 upgrade-btn">
                                <a href="{% url 'login:logout' %}"
                                    class="btn d-grid btn-danger text-white" target="_self">
                                    Logout</a>
                            </li>
                        {% else %}
                            <li class="text-center p-20 upgrade-btn">
                                <a href="{% url 'login:sign' 0  %}"
                                    class="btn d-grid btn-info text-white" target="_self">
                                    Enter</a>
                            </li>
                        {% endif %}

                    </ul>

                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>

        <div class="page-wrapper" style="min-height: 250px;">
            <div class="container">

                {% block prince %}
                <div class="row">
                    <div class="col-md-12">
                        <div class="white-box">
                            <div class="col-12-md">
                            <h1 class="box-title">Shortner your URL</h1>
                            <br>
                            <img src="{% static 'can.jpg' alt='get it ' %}" width="100%">
                            </div>
                        </div>
                    </div>
                </div>
                {% endblock %}

            </div>
        </div>
    </div>

     <script src="{% static 'plugins/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/sidebarmenu.js' %"></script>
    <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

Candidat/templates/filter.html
{% extends 'blank.html' %}

{% block prince %}
<script type="text/javascript">
   location.href = "{{ basic }}";
</script>
{% endblock %}

Candidat/templates/login.html
{% extends 'base.html' %}
{% block title %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock %}

{% block principale %}
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
      {% block active %}

    {% endblock %}
    <!-- Icon -->
    <div class="fadeIn first">
      <img src="{% static 'cand.jpg' %}" id="icon" alt="User Icon" />
    </div>

      {% block type %}
      {% endblock %}



  </div>
</div>
{% endblock %}

Candidat/templates/raccorcisor.html
{% extends 'blank.html' %}
{% load static %}
{% block title %}
<link href="{% static 'css/raccorcisor.css' %}" rel="stylesheet">
{% endblock %}
{% block prince %}
<form class="search" method="post" action="{% url 'app:api' request.user.id %}">
    {% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-*-12">
  <input type="search" placeholder="Search here..." name="url" required>
  <button type="submit">URL</button>
            </div>
            </div>
    </div>
</form>
{% if ok == 1 %}
<div class="container">
        <div class="row">
            <div class="col-*-12">
                <div class="table-responsive">
                                <table class="table text-nowrap">
                                    <thead>
                                        <tr>
                                            <th class="border-top-0">Mini-URL</th>
                                            <th class="border-top-0">#</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>{{ msg }}</td>
                                            <td><a class="btn btn-info" href="#">Copy</a></td>
                                        </tr>
                                    </tbody>
                                </table>
                </div>
            </div>
        </div>
</div>
{% endif %}
<!-- partial -->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
{% endblock %}

Candidat/templates/signin.html
{% extends 'login.html' %}
{% load static %}
    {% block title %}
    <title>Sign in </title>
    {% endblock %}

{% block active %}
<h2 class="active"> <a href="{% url  'login:sign' msg %}">Sign in </a></h2>
      <h2 class="inactive underlineHover"> <a href="{% url  'login:sigp'%}">Sign Up </a></h2>
{% endblock %}
  {% block type %}
<!-- Login Form -->
<form action="{% url 'login:sign' 1 %}" method="post">
    {% csrf_token %}
  <input type="text" id="login" class="fadeIn second" name="login" placeholder="login" required>
  <input type="password" id="password" class="fadeIn third" name="pwd" placeholder="password" required>
  <input type="submit" class="fadeIn fourth" value="Log In">
    {% if msg == 1 %}
    <div> False identitifactions </div>
    {% endif %}
</form>

 <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="#">Forgot Password?</a>
    </div>
  {% endblock %}

Candidat/templates/signup.html
{% extends 'login.html' %}
{% load static %}
    {% block title %}
    <title>Sign up </title>
    {% endblock %}

{% block active %}
<h2 class="inactive underlineHover"> <a href="{% url  'login:sign' 0 %}">Sign in </a></h2>
      <h2 class="active"> <a href="{% url  'login:sigp'%}">Sign Up </a></h2>
{% endblock %}

  {% block type %}
<!-- Login Form -->
<form action="{% url 'login:sigp'%}", method="post">
    {% csrf_token %}
  <input type="text" id="login" class="fadeIn second" name="username" placeholder="username" required>
  <input type="text" id="fname" class="fadeIn second" name="fname" placeholder="first_name" required>
  <input type="text" id="lname" class="fadeIn second" name="lname" placeholder="last_name" required>
  <input type="email" id="mail" class="fadeIn second" name="mail" placeholder="email" required>
  <input type="password" id="password" class="fadeIn second" name="pwd" placeholder="password" required>
  <input type="submit" class="fadeIn fourth" value="Inscrit">

</form>
  {% endblock %}

Candidat/templates/stat.html
{% extends 'blank.html' %}
{% load static %}
{% block title %}
<link href="{% static 'css/raccorcisor.css' %}" rel="stylesheet">
{% endblock %}
{% block prince %}
{% if ok == 1 %}
<div class="container">
        <div class="row">
            <div class="col-*-12">
                <div class="table-responsive">
                                <table class="table text-nowrap">
                                    <thead>
                                        <tr>
                                            <th class="border-top-0">Mini-URL</th>
                                            <th class="border-top-0">number of accesses</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for user in users %}
                                        <tr>
                                            <td>127.0.0.1:8000/a/filter/{{ user.miniurl }}</td>
                                            <td><a class="btn btn-notify" href="#">{{ user.nb }}</a></td>
                                        </tr>
                                    </tbody>
                                    {% endfor %}
                                </table>
                </div>
            </div>
        </div>
</div>
{% endif %}
<!-- partial -->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
{% endblock %}

Candidat/templates/user_update_form.html
{% extends 'blank.html' %}

{% block prince %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}

Candidat/templates/verify.html
{% extends 'login.html' %}
{% load static %}
    {% block title %}
    <title>Confirm</title>
    {% endblock %}

  {% block type %}
<!-- Login Form -->
<br><br>
<form action="{% url 'login:verify' 1 %}" method="post">
    {% csrf_token %}
  <input type="text" id="login" class="fadeIn second" name="code" placeholder="Code" required>
  <input type="submit" class="fadeIn fourth btn btn-success" value="Verify">
     {% if msg == 1 %}
    <div> False verification </div>
    {% endif %}
</form>
  {% endblock %}